export const  secteurDatas  = [
"Services Professionnels",
"Commerce de Détail",
"Restauration et Alimentation",
"Santé et Bien-être",
"Services Financiers",
"Technologie de l'Information",
"Bâtiment et Construction",
"Éducation et Formation",
"Tourisme et Hébergement",
"Services Créatifs",
"Agriculture et Agroalimentaire",
"Commerce en Ligne / E-commerce",
"Services Immobiliers",
"Transport et Logistique",
"Industrie Manufacturière",
"Arts et Divertissement",
"Services Environnementaux",
"Énergie et Ressources Naturelles",
"Mode et Textile",
"Télécommunications",
"Services aux Entreprises",
"Ingénierie et Architecture",
"Juridique et Conseil",
"Marketing et Publicité",
"Associations à But Non Lucratif",
"Automobile",
"Sciences et Recherche",
"Événementiel",
"Sports et Loisirs",
"Autre",
  ];
  /* fait le trie et regroupe moi les éléments de cette liste par secteur d'activité : 
  " */


  /* export const  secteurDatas  = [
    "Achats",
    "Actuariat",
    "Administration Publique",
    "Agriculture",
    "Agroalimentaire",
    "Agences de Communication",
    "Ameublement",
    "Animation",
    "Apiculture",
    "Approvisionnement",
    "Audiovisuel",
    "Audit",
    "Banque",
    "Base de Données",
    "Beauté Cosmétique Esthétique",
    "Bien Être",
    "Biologie",
    "Boulangerie",
    "BTP",
    "Bureautique",
    "Business Intelligence",
    "Cyber-Cafés",
    "Chimie",
    "Cinéma",
    "Commerce",
    "Communication Audiovisuel",
    "Comptabilité",
    "Décoration",
    "Défense",
    "Design",
    "Droit",
    "E-Commerce",
    "Environnement",
    "Education",
    "Electroménager",
    "Electronique",
    "Elevage",
    "Energie",
    "Enquêteurs",
    "Enseignement",
    "Entreposage",
    "Evénementiel",
    "Finance",
    "Fitness",
    "Fonction Publique",
    "Formation",
    "Gaz",
    "Grande Distribution",
    "Hôtellerie Restauration",
    "Humanitaire",
    "Hypermarchés",
    "Immobilier",
    "Import-Export",
    "Imprimerie",
    "Industrie",
    "Journalisme",
    "Juridique",
    "Logistique",
    "Loisirs",
    "Maintenance",
    "Marketing Communication",
    "Mécanique",
    "Médecine",
    "Média",
    "Mode",
    "Numérique Multimédia",
    "Nutrition",
    "Notaire",
    "Pêche",
    "Recherche Développement",
    "Ressources Humaines",
    "Secrétariat Assistanat",
    "Secteur Public",
    "Secteur Sanitaire",
    "Sécurité",
    "Services d´Assainissement",
    "Superettes",
    "Supermarchés",
    "Support Informatique",
    "Textile Habillement",
    "Transport",
    "Vente",
    "Voyages",
  ]; */










